# Generated by Django 5.2.7 on 2025-10-29 18:40

from django.db import migrations

def add_sample_data(apps, schema_editor):
    EducationEntry = apps.get_model('api', 'EducationEntry')
    ExperienceEntry = apps.get_model('api', 'ExperienceEntry')
    Project = apps.get_model('api', 'Project')
    ResearchPublication = apps.get_model('api', 'ResearchPublication')
    HomeData = apps.get_model('api', 'HomeData')
    BlogsData = apps.get_model('api', 'BlogsData')
    ResearchIcon = apps.get_model('api', 'ResearchIcon')

    # Create Education entries
    education_data = [
        {
            "institution": "BRAC University",
            "degree": "Master's degree",
            "field_of_study": "Computer Science",
            "education_type": "Graduate",
            "start_date": "Mar 2024",
            "end_date": "Aug 2025",
            "grade": "3.75",
            "grade_scale": "4.00",
            "location": "Dhaka, Bangladesh",
            "is_current": True,
            "institution_logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/40/BRAC_University_monogram.svg/1024px-BRAC_University_monogram.svg.png",
            "description": "Specializing in advanced topics such as Machine Learning, Cloud Computing, and Distributed Systems.",
            "achievements": ["Maintained CGPA 3.75", "Conducted research on decentralized recommendation systems"],
            "is_visible": True,
            "display_order": 1
        }
    ]

    for edu in education_data:
        EducationEntry.objects.create(**edu)

    # Create Experience entries
    experience_data = [
        {
            "company_name": "LEADS Corporation Limited",
            "role": "Senior Software Engineer",
            "employment_type": "Full-time",
            "location": "Dhaka, Bangladesh",
            "work_mode": "On-site",
            "start_date": "Oct 2025",
            "is_current": True,
            "description": "Working as a Senior Software Engineer focusing on scalable enterprise-grade banking applications using Java, Spring Boot, and Microservices architecture.",
            "achievements": [
                "Implemented secure microservice communication architecture using RabbitMQ and Redis.",
                "Optimized Oracle-based data pipelines for large-scale banking transactions.",
                "Applied SOLID design principles to modernize legacy systems."
            ],
            "skills": [
                "Spring Boot", "Java", "Banking", "Microservices", "Redis", "RabbitMQ",
                "SOLID Design Principles", "Git", "Oracle Database"
            ],
            "tech_stack": ["Java 17", "Spring Boot", "Redis", "RabbitMQ", "Oracle", "Git"],
            "is_visible": True,
            "display_order": 1
        }
    ]

    for exp in experience_data:
        ExperienceEntry.objects.create(**exp)

    # Create Project entries
    projects_data = [
        {
            "slug": "askken-ai",
            "title": "AskKen.ai",
            "organization": "InalyZe Bangladesh Ltd.",
            "role": "Lead Backend Developer",
            "start_date": "Sep 2024",
            "type": "Professional",
            "short_description": "Advanced multi-tenant document intelligence platform for enterprise document management and AI chatbot automation.",
            "responsibilities": [
                "Led backend architecture design using FastAPI and PostgreSQL.",
                "Integrated document processing pipeline with Amazon S3 and Pinecone vector database.",
                "Developed AI chatbot with React and OpenAI integration for intelligent querying."
            ],
            "achievements": [
                "Reduced document query latency by 40% using vector optimization.",
                "Enabled support for 1M+ document embeddings.",
                "Enhanced multi-tenant scalability with database sharding."
            ],
            "skills": [
                "FastAPI", "Python", "PostgreSQL", "Amazon S3", "Pinecone", "Docker",
                "Kubernetes", "LLM Integration", "Prompt Engineering", "React"
            ],
            "tech_stack": {
                "backend": ["FastAPI", "Python", "PostgreSQL"],
                "frontend": ["React"],
                "ai_integration": ["OpenAI API", "Pinecone", "LangChain"],
                "devops": ["Docker", "Kubernetes", "Azure", "AWS"]
            },
            "project_url": "https://askken.ai",
            "contributor_count": 4,
            "collaboration": "Led a team of 3 engineers and 1 designer.",
            "tags": ["AI", "LLM", "Enterprise SaaS", "Multi-Tenant Architecture"],
            "is_visible": True,
            "display_order": 1
        }
    ]

    for proj in projects_data:
        Project.objects.create(**proj)

    # Create Research Publication entries
    research_data = [
        {
            "slug": "skin-cancer-cnn-research",
            "title": "Application of Deep Convolutional Neural Network in Multiclass Skin Cancer Classification Using Custom CNN Architecture",
            "authors": [
                "Nadia Shafique",
                "Kaynat Bint Shaheen",
                "Zarjis Husain Sikder",
                "Utsho Dey",
                "Sharforaz Rahman Swacha"
            ],
            "publication_date": "2023",
            "institution": "Brac University",
            "publication_type": "Undergraduate Thesis / Research Paper",
            "description": "This research proposes a custom CNN architecture for the classification of multiple skin diseases using 28x28 RGB images from the HAM10000 dataset.",
            "objectives": [
                "Develop a custom CNN model for multiclass skin disease classification.",
                "Compare performance with pre-trained models.",
                "Reduce training time and parameter complexity for efficient deployment."
            ],
            "dataset": "HAM10000",
            "metrics": ["Accuracy", "Precision", "Recall", "F1-Score"],
            "comparison_models": ["ResNet50", "EfficientNetB0", "EfficientNetB2"],
            "results_summary": "The proposed model achieved higher test accuracy with fewer trainable parameters and faster training per epoch than existing pre-trained models.",
            "highlights": [
                "Improved test accuracy and reduced test loss.",
                "Lightweight model with lower computational requirements.",
                "Demonstrates potential for clinical diagnostic deployment."
            ],
            "tags": ["Deep Learning", "CNN", "Medical Imaging", "Healthcare AI", "Computer Vision"],
            "is_visible": True,
            "display_order": 1
        }
    ]

    for research in research_data:
        ResearchPublication.objects.create(**research)

    # Create HomeData
    HomeData.objects.create(
        data={
            "hero": {
                "name": "Utsho Dey",
                "tagline": "Senior Software Engineer | AI/ML Enthusiast | Full-Stack Developer",
                "bio": "Passionate about building scalable backend systems, integrating AI solutions, and solving complex engineering challenges.",
                "profile_image": "/images/profile.jpg"
            },
            "social_links": {
                "github": "https://github.com/UtshoDeyTech",
                "linkedin": "https://www.linkedin.com/in/utshodey/",
                "email": "utshodey@example.com",
                "scholar": "https://scholar.google.com"
            }
        }
    )

    # Create BlogsData
    BlogsData.objects.create(
        metadata={
            "site_title": "Tech Blog",
            "site_description": "Insights on Software Development, AI, and Technology",
            "posts_per_page": 6,
            "author_default": "Utsho Dey",
            "author_image_default": "/images/profile.jpg"
        },
        blogs=[],
        future_topics=[
            {
                "topic": "Machine Learning & AI",
                "description": "Deep dives into ML algorithms, LLM integration, prompt engineering, and practical AI applications in real-world projects.",
                "icon": "🤖"
            },
            {
                "topic": "Backend Development",
                "description": "Best practices for building scalable backend systems with Python, FastAPI, Spring Boot, microservices architecture, and database optimization.",
                "icon": "⚙️"
            }
        ]
    )

    # Create Research Icons
    research_icons_data = {
        "computer-science": {
            "path": "M9 17.25v1.007a3 3 0 0 1-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0 1 15 18.257V17.25m6-12V15a2.25 2.25 0 0 1-2.25 2.25H5.25A2.25 2.25 0 0 1 3 15V5.25m18 0A2.25 2.25 0 0 0 18.75 3H5.25A2.25 2.25 0 0 0 3 5.25m18 0V12H3V5.25",
            "title": "Computer Science"
        },
        "mathematics": {
            "path": "M15.75 15.75V18m-7.5-6.75h.008v.008H8.25v-.008zm0 2.25h.008v.008H8.25V13.5zm0 2.25h.008v.008H8.25v-.008zm0 2.25h.008v.008H8.25V18zm2.498-6.75h.007v.008h-.007v-.008zm0 2.25h.007v.008h-.007V13.5z",
            "title": "Mathematics"
        }
    }

    for key, data in research_icons_data.items():
        ResearchIcon.objects.create(key=key, path=data["path"], title=data["title"])

def remove_sample_data(apps, schema_editor):
    EducationEntry = apps.get_model('api', 'EducationEntry')
    ExperienceEntry = apps.get_model('api', 'ExperienceEntry')
    Project = apps.get_model('api', 'Project')
    ResearchPublication = apps.get_model('api', 'ResearchPublication')
    HomeData = apps.get_model('api', 'HomeData')
    BlogsData = apps.get_model('api', 'BlogsData')
    ResearchIcon = apps.get_model('api', 'ResearchIcon')

    EducationEntry.objects.all().delete()
    ExperienceEntry.objects.all().delete()
    Project.objects.all().delete()
    ResearchPublication.objects.all().delete()
    HomeData.objects.all().delete()
    BlogsData.objects.all().delete()
    ResearchIcon.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_data, remove_sample_data),
    ]
