# Generated by Django 5.2.8 on 2025-11-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Subscriber email address', max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether subscription is active')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at subscription time', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent at subscription time')),
                ('confirmed', models.BooleanField(default=False, help_text='Email confirmed via verification link')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When user unsubscribed', null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='api_newslet_email_7d016c_idx'), models.Index(fields=['-subscribed_at'], name='api_newslet_subscri_64cbe2_idx')],
            },
        ),
    ]
