# Generated by Django 5.2.8 on 2025-11-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='default_page_size',
            field=models.IntegerField(default=10, help_text='Default number of blog posts to show per page. Default: 10'),
        ),
    ]
