# Generated by Django 5.2.7 on 2025-11-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_insert_full_dummy_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('excerpt', models.TextField(blank=True, help_text='Short description/summary of the blog')),
                ('content_markdown', models.TextField(help_text='Blog content in Markdown format')),
                ('cover_image', models.URLField(blank=True)),
                ('featured_image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('author', models.CharField(default='Admin', max_length=255)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('likes', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False, help_text='Publish this blog')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('is_trending', models.BooleanField(default=False, help_text='Mark as trending')),
                ('is_editor_choice', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated read time in minutes')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', 'display_order'],
            },
        ),
    ]
