# Generated by Django 5.2.8 on 2025-11-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='Device fingerprint', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('liked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if user unliked')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_records', to='api.blog')),
            ],
            options={
                'verbose_name': 'Blog Like',
                'verbose_name_plural': 'Blog Likes',
                'ordering': ['-liked_at'],
                'indexes': [models.Index(fields=['blog', 'fingerprint', 'is_active'], name='api_bloglik_blog_id_b5b41a_idx'), models.Index(fields=['liked_at'], name='api_bloglik_liked_a_08b637_idx')],
                'unique_together': {('blog', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='Device fingerprint', max_length=255)),
                ('session_id', models.CharField(blank=True, help_text='Browser session ID', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='api.blog')),
            ],
            options={
                'verbose_name': 'Blog View',
                'verbose_name_plural': 'Blog Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['blog', 'fingerprint'], name='api_blogvie_blog_id_7ef483_idx'), models.Index(fields=['viewed_at'], name='api_blogvie_viewed__720d55_idx')],
                'unique_together': {('blog', 'fingerprint')},
            },
        ),
    ]
