# Generated by Django 5.2.8 on 2025-11-09 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bloglike_blogview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_update_interval', models.IntegerField(default=300, help_text='How often to update duration tracking (in seconds). Default: 300 (5 minutes)')),
                ('inactivity_threshold', models.IntegerField(default=120, help_text='How long before considering user inactive (in seconds). Default: 120 (2 minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Settings',
                'verbose_name_plural': 'Blog Settings',
            },
        ),
        migrations.RemoveIndex(
            model_name='blogview',
            name='api_blogvie_blog_id_7ef483_idx',
        ),
        migrations.AlterUniqueTogether(
            name='blogview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blogview',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Total time spent on this blog (in seconds)'),
        ),
        migrations.AddField(
            model_name='blogview',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Last time user was on this blog'),
        ),
        migrations.AddField(
            model_name='blogview',
            name='viewed_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Date of view (for daily tracking)'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='blogview',
            unique_together={('blog', 'fingerprint', 'viewed_date')},
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['blog', 'fingerprint', 'viewed_date'], name='api_blogvie_blog_id_bd811d_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['last_seen'], name='api_blogvie_last_se_a9b9b4_idx'),
        ),
    ]
