# Generated by Django 5.2.8 on 2025-11-10 15:14

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(help_text='Custom URL slug for accessing this file', max_length=255, unique=True)),
                ('file', models.FileField(help_text='Upload file (image, audio, video, document, etc.)', upload_to=api.models.secure_file_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], db_index=True, default='image', max_length=20)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename when uploaded', max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Optional title/description', max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for images (accessibility)', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True, help_text='If false, file requires authentication')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['slug'], name='api_mediafi_slug_e50aef_idx'), models.Index(fields=['uuid'], name='api_mediafi_uuid_bf91bb_idx'), models.Index(fields=['file_type', '-uploaded_at'], name='api_mediafi_file_ty_e8ac84_idx')],
            },
        ),
    ]
