# Generated by Django 5.2.8 on 2025-11-10 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mediafile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homedata',
            options={'verbose_name': 'Home Page Data', 'verbose_name_plural': 'Home Page Data'},
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='data',
        ),
        migrations.AddField(
            model_name='homedata',
            name='about_highlights',
            field=models.JSONField(default=list, help_text='List of key highlights'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='about_paragraphs',
            field=models.JSONField(default=list, help_text='List of paragraphs for about section'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='about_title',
            field=models.CharField(default='About Me', max_length=255),
        ),
        migrations.AddField(
            model_name='homedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homedata',
            name='cta_paragraph',
            field=models.TextField(blank=True, default="I'm always open to discussing new projects, creative ideas, or opportunities to be part of your vision."),
        ),
        migrations.AddField(
            model_name='homedata',
            name='cta_primary_text',
            field=models.CharField(blank=True, default='Get In Touch', max_length=100),
        ),
        migrations.AddField(
            model_name='homedata',
            name='cta_primary_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='homedata',
            name='cta_secondary_text',
            field=models.CharField(blank=True, default='View Portfolio', max_length=100),
        ),
        migrations.AddField(
            model_name='homedata',
            name='cta_secondary_url',
            field=models.CharField(blank=True, default='/project', max_length=500),
        ),
        migrations.AddField(
            model_name='homedata',
            name='cta_title',
            field=models.CharField(blank=True, default="Let's Work Together", max_length=255),
        ),
        migrations.AddField(
            model_name='homedata',
            name='hero_bio',
            field=models.TextField(default='Your bio'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='hero_cta_primary_text',
            field=models.CharField(blank=True, default='View My Work', max_length=100),
        ),
        migrations.AddField(
            model_name='homedata',
            name='hero_cta_primary_url',
            field=models.CharField(blank=True, default='/project', max_length=500),
        ),
        migrations.AddField(
            model_name='homedata',
            name='hero_cta_secondary_text',
            field=models.CharField(blank=True, default='Contact Me', max_length=100),
        ),
        migrations.AddField(
            model_name='homedata',
            name='hero_cta_secondary_url',
            field=models.CharField(blank=True, default='mailto:your@email.com', max_length=500),
        ),
        migrations.AddField(
            model_name='homedata',
            name='hero_name',
            field=models.CharField(default='Your Name', max_length=255),
        ),
        migrations.AddField(
            model_name='homedata',
            name='hero_profile_image',
            field=models.URLField(blank=True, help_text='URL to profile image (can use CDN URL)'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='hero_resume_url',
            field=models.URLField(blank=True, help_text='URL to resume PDF'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='hero_tagline',
            field=models.CharField(default='Your Tagline', max_length=500),
        ),
        migrations.AddField(
            model_name='homedata',
            name='show_blog',
            field=models.BooleanField(default=True, help_text='Show blog section on home page'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='show_education',
            field=models.BooleanField(default=True, help_text='Show education section on home page'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='show_experience',
            field=models.BooleanField(default=True, help_text='Show experience section on home page'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='show_projects',
            field=models.BooleanField(default=True, help_text='Show projects section on home page'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='show_research',
            field=models.BooleanField(default=True, help_text='Show research section on home page'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='skills_categories',
            field=models.JSONField(default=list, help_text='List of skill categories with name, icon, and skills list'),
        ),
        migrations.AddField(
            model_name='homedata',
            name='skills_title',
            field=models.CharField(default='Technical Skills', max_length=255),
        ),
        migrations.AddField(
            model_name='homedata',
            name='social_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='homedata',
            name='social_github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homedata',
            name='social_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homedata',
            name='social_scholar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homedata',
            name='social_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homedata',
            name='stats_projects_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homedata',
            name='stats_publications',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homedata',
            name='stats_technologies_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homedata',
            name='stats_years_of_experience',
            field=models.CharField(blank=True, help_text="e.g., '2+', '5'", max_length=20),
        ),
        migrations.AddField(
            model_name='homedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
