# Generated by Django 5.2.8 on 2025-11-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_homedata_options_remove_homedata_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedata',
            name='hero_profile_image',
            field=models.CharField(blank=True, help_text='URL to profile image (can use CDN URL or relative path)', max_length=500),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='hero_resume_url',
            field=models.CharField(blank=True, help_text='URL to resume PDF (can be relative like /resume.pdf)', max_length=500),
        ),
    ]
